# Generated by Django 6.0.5 on 2026-06-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_librarian',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LIBRARIAN', 'Librarian'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
