# Generated by Django 5.2.7 on 2026-06-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address_user_dob_user_gender_user_member_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member_type',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Librarian', 'Librarian')], max_length=20, null=True),
        ),
    ]
