# Generated by Django 5.2.7 on 2026-06-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='borrowbook',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Pending', 'Pending')], default='Borrowed', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateField(),
        ),
    ]
