# Generated by Django 5.2.7 on 2026-06-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_borrowbook_fine_remove_borrowbook_is_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='fine_amount',
            field=models.IntegerField(default=0),
        ),
    ]
